[env]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c6
framework = arduino

build_flags =
    -std=gnu++20
    -fno-rtti ; needed if we do dynamic_cast or typeid

    -Ilib/color/src/color/include

build_src_flags =
    -Wall
    -Wextra
    -Werror


[env:debug]
build_type = debug

build_flags =
    ${env.build_flags}
    -fexceptions ; only in debug mode, to get better error messages and stack traces

[env:release]
build_type = release

build_flags =
    ${env.build_flags}
    -fno-exceptions ; assume no exceptions to reduce code size and improve performance
    